# Generated by Django 3.1.7 on 2021-03-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='chatroom', to='chat.User'),
        ),
    ]
