# Generated by Django 3.1.7 on 2021-03-22 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210317_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='verCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=6)),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='chat.user')),
            ],
            options={
                'db_table': 'ver_code',
            },
        ),
    ]
