# Generated by Django 3.1.7 on 2021-03-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_vercode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vercode',
            name='user',
        ),
        migrations.AddField(
            model_name='vercode',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
