# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startGroup.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(304, 492)
        self.startGroupButton = QtWidgets.QPushButton(Form)
        self.startGroupButton.setGeometry(QtCore.QRect(10, 440, 131, 41))
        self.startGroupButton.setObjectName("startGroupButton")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 60, 281, 361))
        self.listWidget.setObjectName("listWidget")
        self.chooseAllButton = QtWidgets.QPushButton(Form)
        self.chooseAllButton.setGeometry(QtCore.QRect(160, 440, 61, 41))
        self.chooseAllButton.setObjectName("chooseAllButton")
        self.cancleChooseAllButton = QtWidgets.QPushButton(Form)
        self.cancleChooseAllButton.setGeometry(QtCore.QRect(230, 440, 61, 41))
        self.cancleChooseAllButton.setObjectName("cancleChooseAllButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.startGroupButton.setText(_translate("Form", "发起群聊"))
        self.chooseAllButton.setText(_translate("Form", "全选"))
        self.cancleChooseAllButton.setText(_translate("Form", "取消"))
        self.lineEdit.setPlaceholderText(_translate("Form", "聊天室名称(必填)"))
