# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(444, 918)
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setGeometry(QtCore.QRect(0, 60, 431, 801))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        self.friendLineEdit = QtWidgets.QLineEdit(Form)
        self.friendLineEdit.setGeometry(QtCore.QRect(10, 10, 201, 41))
        self.friendLineEdit.setObjectName("friendLineEdit")
        self.addFriendPushButton = QtWidgets.QPushButton(Form)
        self.addFriendPushButton.setGeometry(QtCore.QRect(220, 10, 101, 41))
        self.addFriendPushButton.setObjectName("addFriendPushButton")
        self.addFriendPushButton_2 = QtWidgets.QPushButton(Form)
        self.addFriendPushButton_2.setGeometry(QtCore.QRect(330, 10, 101, 41))
        self.addFriendPushButton_2.setObjectName("addFriendPushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "用户列表"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "好友列表"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Form", "New Subitem"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Form", "群列表"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.addFriendPushButton.setText(_translate("Form", "添加好友"))
        self.addFriendPushButton_2.setText(_translate("Form", "发起群聊"))
